import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiOutlineArrowPath,
  HiOutlineSun,
  HiOutlineMoon,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiOutlineLink,
  HiArrowUpRight,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineComputerDesktop,
  HiOutlineQuestionMarkCircle,
  HiOutlineInformationCircle,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  HiOutlineCheckBadge,
  HiOutlineCheckCircle,
  HiOutlineXMark,
  HiOutlineUser,
  HiOutlineEyeDropper,
  HiOutlineMinus,
  HiOutlinePlus,
  HiOutlineCalendar,
  HiOutlineDocumentDuplicate,
  HiOutlineGlobeAlt,
  HiOutlineHome,
  HiOutlineSquares2X2,
  HiOutlineBookOpen,
  HiOutlinePhoto,
  HiOutlineEnvelope,
  HiOutlineArrowRight,
  HiOutlineArrowUpRight as HiOutlineArrowUpRightFromSquare,
  HiPlay,
  HiPause,
  HiSpeakerWave,
  HiSpeakerXMark,
  HiOutlinePhone,
  HiOutlineVideoCamera,
  HiOutlineCodeBracket,
  HiOutlineCpuChip,
  HiOutlineUsers,
  HiOutlineHandRaised,
  HiOutlineRocketLaunch,
  HiOutlineArrowsPointingIn,
  HiOutlineArrowsPointingOut,
} from "react-icons/hi2";

import {
  FaGithub,
  FaLinkedin,
  FaXTwitter,
  FaInstagram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  sun: HiOutlineSun,
  moon: HiOutlineMoon,
  help: HiOutlineQuestionMarkCircle,
  info: HiOutlineInformationCircle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineExclamationCircle,
  checkbox: HiOutlineCheckBadge,
  check: HiOutlineCheckCircle,
  checkCircle: HiOutlineCheckCircle,
  copy: HiOutlineDocumentDuplicate,
  eyeDropper: HiOutlineEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiOutlineUser,
  close: HiOutlineXMark,
  openLink: HiOutlineLink,
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiOutlineArrowRight,
  arrowUpRightFromSquare: HiOutlineArrowUpRightFromSquare,
  minus: HiOutlineMinus,
  plus: HiOutlinePlus,
  calendar: HiOutlineCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  computer: HiOutlineComputerDesktop,
  globe: HiOutlineGlobeAlt,
  home: HiOutlineHome,
  grid: HiOutlineSquares2X2,
  book: HiOutlineBookOpen,
  gallery: HiOutlinePhoto,
  email: HiOutlineEnvelope,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  play: HiPlay,
  pause: HiPause,
  volumeOn: HiSpeakerWave,
  volumeOff: HiSpeakerXMark,
  phone: HiOutlinePhone,
  instagram: FaInstagram,
  video: HiOutlineVideoCamera,
  code: HiOutlineCodeBracket,
  cpu: HiOutlineCpuChip,
  users: HiOutlineUsers,
  handshake: HiOutlineHandRaised,
  rocket: HiOutlineRocketLaunch,
  maximize: HiOutlineArrowsPointingOut,
  minimize: HiOutlineArrowsPointingIn,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
